version: '3'
services:
  app:
    image: satoryu/php-mssql:0.0.1
    volumes:
      - "./:/app:cached"
    ports:
      - "80:8000"
    environment:
      - DB_HOST=sqlsrver
      - DB_PORT=1433
      - DB_DATABASE=blog
      - DB_USERNAME=SA
      - DB_PASSWORD=L@r@v3lbl0g
    depends_on:
      - sqlsrver
  sqlsrver:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=L@r@v3lbl0g