# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: satoryu/php-mssql:0.0.3
        environment:
          - APP_ENV: CI
          - DB_CONNECTION: sqlsrv
          - DB_HOST: 127.0.0.1
          - DB_PORT: 1433
          - DB_DATABASE: blog
          - DB_USERNAME: SA
          - DB_PASSWORD: L@r@v3lbl0g
      - image: microsoft/mssql-server-linux:2017-CU8
        environment:
          - ACCEPT_EULA: Y
          - SA_PASSWORD: L@r@v3lbl0g

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Create Database
          command: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'L@r@v3lbl0g' -Q 'create database blog'

      - run: ./bin/composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: Generate application encryption key
          command: |
            cp .env.example .env
            php artisan key:generate

      - run:
          name: Migrate
          command: php artisan migrate

      # run tests!
      - run: ./bin/composer exec -v phpunit